---
title: "Dashboard"
format: dashboard
---

```{r setup, include = F}
# library(flexdashboard)
library(ggplot2)
library(rextor)

knitr::opts_chunk$set(echo = F, warning = F)

# Calculate all the CRAN download values

## dropR
downloads <- cranlogs::cran_downloads("dropR", from = "2015-01-01", to = Sys.Date())

alltime <- downloads$count |> sum()

lastmonth <- cranlogs::cran_downloads("dropR", when = "last-month")$count |> sum()

yesterday <- cranlogs::cran_downloads("dropR", when = "last-day")$count

lastweekdailymax <- cranlogs::cran_downloads("dropR", when = "last-week")$count |> max()

## rextor

downloadsrextor <- cranlogs::cran_downloads("rextor", from = "2026-05-20", to = Sys.Date())
alltimerextor <- downloadsrextor$count |> sum()

maxnumrextor <- max(downloadsrextor$count)
datemaxnumrextor <- downloadsrextor$date[downloadsrextor$count == max(downloadsrextor$count)]
```

# dropR

## dropR downloads {height="40%"}

```{r}
#| content: valuebox
#| title: "All time dropR downloads"

list(
  icon = "download",
  color = "info",
  value = alltime
)
```

```{r}
#| content: valuebox
#| title: "Last month's dropR downloads"

list(
  icon = "clock-history",
  color = "info",
  value = lastmonth
)
```

```{r}
# #| title: "Yesterday's dropR downloads"
# #| layout-ncol: 3 

yday <- Sys.Date()-2

cat("title=", "Last day's dropR downloads (", yday|> as.character(), "), compared to last week's maximum number of downloads")

# Daily
flexdashboard::gauge(yesterday, min = 0, max = lastweekdailymax, flexdashboard::gaugeSectors(  #symbol = '%',
  success = c(lastweekdailymax/2+1, lastweekdailymax), danger = c(0, lastweekdailymax/2) #warning = c(33, 66),
))
```

## download history {height="60%"}

```{r}
#| fig-width: 18
#| fig-height: 4
#| out-width: "100%"

useR <- as.Date("2024-07-09")

brm <- as.Date("2025-07-18")

# library(unikn)


ggplot(downloads, aes(x = date, y = count, color = count)) +
  geom_line() +
  geom_vline(xintercept = as.numeric(useR), color = "#2ebdc2", size = 1.2) +
  geom_text(x = useR-170, y = 90, label = "Presented @ useR", color = "#2ebdc2") +
  geom_vline(xintercept = as.numeric(brm), color = "#0d4c6b", size = 1.2) +
  geom_text(x = brm-150, y = 90, label = "Published in BRM", color = "#0d4c6b") +
  theme_minimal() +
  labs(x = " ", y = "Downloads from CRAN") +
  coord_cartesian(xlim = c(downloads$date[1], downloads$date[nrow(downloads)]), 
                  expand = FALSE, clip = "off") +
  # rextor::scale_rextor(pal = 5) +
  scale_color_continuous(palette = c("#750400", "#f7ad00", "#58015e", "#0006b8", "#00d9ce"))+
  theme(legend.position = "none")


```

# rextor

## text and downloads {height="40%"}

:::{.card title="rextor package"}

`rextor` was first released to CRAN on May 21st 2026.
Read more about it under [Blog](./blog.html) or on the official [CRAN page](https://doi.org/10.32614/CRAN.package.rextor).


Since then, the maximum number of daily downloads was `r maxnumrextor` on `r datemaxnumrextor`.


:::

```{r}
#| content: valuebox
#| title: "All time rextor downloads"

list(
  icon = "download",
  color = "#a3d88a",
  value = alltimerextor
)
```


## download history {height="60%"}

```{r}
#| fig-width: 18
#| fig-height: 4
#| out-width: "100%"

ggplot(downloadsrextor, aes(x = date, y = count, color = count)) +
  geom_line() +
  theme_minimal() +
  labs(x = " ", y = "Downloads from CRAN") +
  coord_cartesian(xlim = c(downloadsrextor$date[1], downloadsrextor$date[nrow(downloadsrextor)]+3), 
                  expand = FALSE, clip = "off") +
  scale_rextor(pal = 5) +
  theme(legend.position = "none")
```
